---
title: "data_wrangling_ii"
output: html_document
date: "2023-10-12"
---

load the necessary libraries

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

Import NDSUH data

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_url = 
  read_html(nsduh_url)
```

```{r}
nsduh_url |>
  html_table()
```

```{r}
marj_use_df =
 nsduh_url |>
  html_table()|>
  first() |>
  slice(-1)
```

import star wars 

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = 
  read_html(swm_url)
```

```{r}
swm_title_vec = 
swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()
```

```{r}
swm_gross_rev_vec = 
swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()
```

```{r}
swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
  
```

## API

get water data from NYC

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |>
  content("parsed")
```

BRFSS DATA

```{r}
brfss_dF = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit" = 5000)) |>
  content()
```

Try it now

```{r}
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()
```



